# 12-app-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: investbrain-storage
  namespace: investbrain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-amd64
