apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-config
  namespace: kube-system
data:
  dnsmasq.conf: |
    no-resolv
    server=8.8.8.8         # Forward queries to Google DNS
    server=192.168.1.1     # Or your router/local DNS server
    cache-size=1000        # Cache up to 1000 queries
    log-queries
    address=/home.local/192.168.1.12  # Map home.local to a specific IP
