apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-external
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: dnsmasq-service
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 3053  # Accessible on <NodeIP>:3053
