apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-external-service
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: dnsmasq
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 30053  # Accessible on <NodeIP>:3053
