apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-service
  namespace: kube-system
spec:
  selector:
    app: dnsmasq
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
#  clusterIP: 10.0.0.53  # Assign a static ClusterIP (optional)
  