apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss-postgres
  namespace: freshrss
  labels:
    app.kubernetes.io/name: freshrss
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: home-infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: freshrss
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: freshrss
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: home-infrastructure
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: freshrss-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: freshrss-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: freshrss-secrets
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - freshrss
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - freshrss
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: freshrss-postgres-pvc
      nodeSelector:
        kubernetes.io/arch: arm64
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss-postgres
  namespace: freshrss
  labels:
    app.kubernetes.io/name: freshrss
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: home-infrastructure
spec:
  selector:
    app.kubernetes.io/name: freshrss
    app.kubernetes.io/component: database
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-postgres-pvc
  namespace: freshrss
  labels:
    app.kubernetes.io/name: freshrss
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: home-infrastructure
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn