apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      nodeSelector:
        kubernetes.io/hostname: dell-192-168-1-7
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 8123
        volumeMounts:
        - name: config
          mountPath: /config
        - name: custom-config
          mountPath: /config/packages/custom.yaml
          subPath: custom.yaml
        - name: zigbee
          mountPath: /dev/zigbee
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant-config
      - name: custom-config
        configMap:
          name: home-assistant-custom-config
      - name: zigbee
        hostPath:
          path: /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_02b6b3d219a1f011815e2c81bb936ffa-if00-port0
          type: CharDevice