apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sjgorey/home-arcocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    sync-options:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true