# Architecture-specific StorageClasses for Longhorn
# These allow you to create volumes that will be placed on specific CPU architectures

---
# StorageClass for AMD64/x86_64 nodes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-amd64
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/component: storageclass
    architecture: amd64
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer  # Wait for pod scheduling to respect node selectors
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  # Note: Architecture-specific placement is handled by pod nodeSelector + volumeBindingMode: WaitForFirstConsumer

---
# StorageClass for ARM64 nodes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-arm64
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/component: storageclass
    architecture: arm64
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer  # Wait for pod scheduling to respect node selectors
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  # Note: Architecture-specific placement is handled by pod nodeSelector + volumeBindingMode: WaitForFirstConsumer

# ---
# # StorageClass for specific node zones/regions
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: longhorn-zone-a
#   labels:
#     app.kubernetes.io/name: longhorn
#     app.kubernetes.io/component: storageclass
#     zone: zone-a
# provisioner: driver.longhorn.io
# allowVolumeExpansion: true
# reclaimPolicy: Delete
# volumeBindingMode: WaitForFirstConsumer
# parameters:
#   numberOfReplicas: "2"  # Reduced replicas for zone-specific storage
#   staleReplicaTimeout: "30"
#   fromBackup: ""
#   fsType: "ext4"
#   dataLocality: "best-effort"
#   # Place volumes only in specific zone
#   nodeSelector: "topology.kubernetes.io/zone=zone-a"

---
# StorageClass with data locality (replicas on same node as workload)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-local
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/component: storageclass
    locality: local
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"  # Explicitly not default
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"  # Single replica for local storage
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "strict-local"  # Keep data on same node as pod

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nvme
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  diskSelector: "nvme"          # ← this is the magic line
  #nodeSelector: "disk-nvme"     # optional: also requires the node itself to have the tag
  fsType: "ext4"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true