apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      containers:
      - name: dnsmasq
        image: jpillora/dnsmasq    # A lightweight dnsmasq container image
        args:
        - --no-daemon
        volumeMounts:
        - name: config-volume
          mountPath: /etc/dnsmasq.conf
          subPath: dnsmasq.conf
      volumes:
      - name: config-volume
        configMap:
          name: dnsmasq-config