# 05-postgres-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: firefly-iii
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        # Fix: Create clean pgdata subdir if not exists
        - name: init-pgdata
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              if [ ! -d /mnt/data/pgdata ]; then
                echo "Creating /mnt/data/pgdata..."
                mkdir -p /mnt/data/pgdata
                chown 999:999 /mnt/data/pgdata
              else
                echo "/mnt/data/pgdata already exists"
              fi
          volumeMounts:
            - name: data
              mountPath: /mnt/data
          securityContext:
            runAsUser: 0
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: PGDATA
              value: /mnt/data/pgdata
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: data
              mountPath: /mnt/data
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Optional: health checks
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "firefly"]
            initialDelaySeconds: 30
            periodSeconds: 10
      securityContext:
        fsGroup: 999  # postgres gid
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data