# 09-firefly-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-storage
  namespace: firefly-iii
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  