# 17-data-importer-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-data-importer-storage
  namespace: firefly-iii
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn