apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-plaid-connector-cursors
  namespace: firefly-iii
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-amd64