apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: n8n-network-policy
  namespace: n8n
  labels:
    app: n8n
spec:
  podSelector:
    matchLabels:
      app: n8n
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress traffic on port 5678 from any namespace
  # This includes Traefik for ingress routing
  - ports:
    - protocol: TCP
      port: 5678
  # Allow ingress for health checks and internal communication
  - from:
    - namespaceSelector: {}  # Allow from any namespace
    ports:
    - protocol: TCP
      port: 5678
  egress:
  # Allow all egress traffic
  - {}