apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator.git
    path: charts/spark-operator
    targetRevision: 1.1.27
    helm:
      values: |
        sparkJobNamespace: spark
        webhook.enable: true
        enableBatchScheduler: true
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
