apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-roles
  namespace: default
data:
  # file-like keys
  roles.yaml: |
    rbac:
      roles:
        - name: "admins"
          clusters:
            - home
          subjects:
            - provider: oauth_github
              type: organization
              value: "gorco-us"
            - provider: oauth_github
              type: user
              value: "sjgorey"
          permissions:
            - resource: applicationconfig
              actions: all
          
            - resource: clusterconfig
              actions: all

            - resource: topic
              value: ".*"
              actions: all

            - resource: consumer
              value: ".*"
              actions: all

            - resource: schema
              value: ".*"
              actions: all

            - resource: connect
              value: ".*"
              actions: all

            - resource: ksql
              actions: all
              
            - resource: acl
              actions: [ view ]
