apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alertmanager-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  alertmanager-datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: AlertManager
      type: alertmanager
      access: proxy
      url: http://kube-prometheus-stack-alertmanager:9093
      jsonData:
        implementation: prometheus
      editable: true