apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: busybox
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
