apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-tools
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server:
      "{ .Values.spec.destination.server }": null
  project:
    "{ .Values.spec.project }": null
  source:
    path: it-tools
    repoURL:
      "{ .Values.spec.source.repoURL }": null
    targetRevision:
      "{ .Values.spec.source.targetRevision }": null
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
