apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: christmas-quiz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sjgorey/home-argocd-app-config
    targetRevision: HEAD
    path: apps/quiz/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: quiz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
