apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: paperless-ngx-network-policy
  namespace: paperless-ngx
  labels:
    app: paperless-ngx
spec:
  podSelector:
    matchLabels:
      app: paperless-ngx
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress traffic from any namespace for web access
  - ports:
    - protocol: TCP
      port: 8000
  # Allow database access from paperless app
  - from:
    - podSelector:
        matchLabels:
          app: paperless-ngx
          component: app
    ports:
    - protocol: TCP
      port: 5432
  # Allow redis access from paperless app
  - from:
    - podSelector:
        matchLabels:
          app: paperless-ngx
          component: app
    ports:
    - protocol: TCP
      port: 6379
  # Allow tika access from paperless app
  - from:
    - podSelector:
        matchLabels:
          app: paperless-ngx
          component: app
    ports:
    - protocol: TCP
      port: 9998
  # Allow gotenberg access from paperless app
  - from:
    - podSelector:
        matchLabels:
          app: paperless-ngx
          component: app
    ports:
    - protocol: TCP
      port: 3000
  egress:
  # Allow all egress traffic
  - {}