apiVersion: v1
kind: ConfigMap
metadata:
  name: https-proxy-cm
  namespace: default
data:
  # file-like keys
  https.conf: |
    acl SSL_ports port 443
    acl Safe_ports port 80
    acl Safe_ports port 443
    acl CONNECT method CONNECT
    http_access allow CONNECT
