apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finance-exporter
  namespace: argocd
  labels:
    app.kubernetes.io/name: finance-exporter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sjgorey/home-argocd-app-config
    path: infrastructure/finance-exporter
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: finance-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  revisionHistoryLimit: 3