apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-iii
  namespace: argocd
  labels:
    app.kubernetes.io/name: firefly
spec:
  project: default
  source:
    repoURL: https://github.com/sjgorey/home-argocd-app-config
    path: infrastructure/firefly-iii
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly-iii
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true