apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  project: default
  source:
    repoURL: https://github.com/sjgorey/home-argocd-app-config
    path: infrastructure/home-assistant
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true