apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    app.kubernetes.io/name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sjgorey/home-argocd-app-config  # Update with your actual repo URL
    path: infrastructure/longhorn
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true  # Recommended for CRDs
      - RespectIgnoreDifferences=true
  revisionHistoryLimit: 3