apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    app.kubernetes.io/name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sjgorey/home-argocd-app-config  # Update with your actual repo URL
    path: infrastructure/longhorn
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true  # Recommended for CRDs
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    # Longhorn CRDs are modified by the Longhorn operator after installation
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: engineimages.longhorn.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /spec/preserveUnknownFields
        - /status
        - /metadata/annotations
        - /metadata/labels
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: nodes.longhorn.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /spec/preserveUnknownFields
        - /status
        - /metadata/annotations
        - /metadata/labels
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: volumes.longhorn.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /spec/preserveUnknownFields
        - /status
        - /metadata/annotations
        - /metadata/labels
    # Catch all other Longhorn CRDs that might have drift
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /spec/preserveUnknownFields
        - /status
        - /metadata/annotations
        - /metadata/labels
  revisionHistoryLimit: 3