apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpz-blocklist
  namespace: unbound
  labels:
    backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: longhorn-amd64