---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ghostfolio
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  clusterIP: None   # headless for StatefulSet
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ghostfolio
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: ghostfolio
  namespace: ghostfolio
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: web
      targetPort: 3333
  selector:
    app: ghostfolio
