apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ghostfolio
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        # Fix: Create clean pgdata subdir if not exists
        - name: init-pgdata
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              if [ ! -d /mnt/data/pgdata ]; then
                echo "Creating /mnt/data/pgdata..."
                mkdir -p /mnt/data/pgdata
                chown 999:999 /mnt/data/pgdata
              else
                echo "/mnt/data/pgdata already exists"
              fi
          volumeMounts:
            - name: data
              mountPath: /mnt/data
          securityContext:
            runAsUser: 0
      nodeSelector:
        kubernetes.io/arch: arm64
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:16  # Official, ARM64 multi-arch
          env:
            - name: PGDATA
              value: /mnt/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /mnt/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
