apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss
  namespace: argocd
  labels:
    app.kubernetes.io/name: freshrss
    app.kubernetes.io/part-of: home-infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/sjgorey/home-argocd-app-config
    targetRevision: HEAD
    path: infrastructure/freshrss
  destination:
    server: https://kubernetes.default.svc
    namespace: freshrss
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m