apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-config
  namespace: default
  labels:
    app: dnsmasq
data:
  dnsmasq.conf: |
    # Basic DNS configuration
    port=53
    
    # Cache settings
    cache-size=1000
    neg-ttl=3600
    local-ttl=600
    
    # Local domain handling
    domain=home.local
    expand-hosts
    
    # DNS forwarders (customize for your ISP)
    server=8.8.8.8
    server=8.8.4.4
    server=1.1.1.1
    server=1.0.0.1
    
    # Local network
    local=/home.local/
    domain-needed
    bogus-priv
    
    # Custom local DNS entries (examples)
    address=/router.home.local/192.168.1.1
    address=/nas.home.local/192.168.1.100
    
    # Kubernetes cluster services - wildcard approach
    # All *.example.com domains point to any cluster node
    address=/example.com/192.168.1.5
    address=/example.com/192.168.1.21
    address=/example.com/192.168.1.22
    address=/example.com/192.168.1.23
    address=/example.com/192.168.1.24
    
    # Or use a single load balancer IP if you have one
    # address=/example.com/192.168.1.100
    
    # Logging
    log-queries
    log-facility=/var/log/dnsmasq.log
    
    # No DHCP - DNS only
    no-dhcp-interface=
    
    # Bind to all interfaces in container
    bind-interfaces
    listen-address=0.0.0.0