apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dnsmasq
  namespace: default
  labels:
    app: dnsmasq
spec:
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      # Only run on x86_64 nodes to avoid ARM compatibility issues
      nodeSelector:
        kubernetes.io/arch: amd64
      
      # Service account
      serviceAccountName: default
      
      containers:
      - name: dnsmasq
        image: jpillora/dnsmasq:latest
        imagePullPolicy: Always
        
        # Resource limits for stability
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        
        # DNS ports with hostPort for standard DNS access
        ports:
        - name: dns-tcp
          containerPort: 53
          hostPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          hostPort: 53
          protocol: UDP
        
        # Health checks
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "nslookup google.com 127.0.0.1 > /dev/null"
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "nslookup google.com 127.0.0.1 > /dev/null"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        
        # Volume mounts
        volumeMounts:
        - name: config
          mountPath: /etc/dnsmasq.conf
          subPath: dnsmasq.conf
          readOnly: true
        - name: cache-storage
          mountPath: /var/lib/dnsmasq
        - name: log-storage
          mountPath: /var/log
        
        # Environment variables
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      
      # Volumes
      volumes:
      - name: config
        configMap:
          name: dnsmasq-config
      - name: cache-storage
        emptyDir: {}
      - name: log-storage
        emptyDir: {}