apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: default
spec:
  selector:
    matchLabels:
      app: curl
  replicas: 1
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: curlimages/curl
