apiVersion: v1
kind: Secret
metadata:
  name: searxng
  namespace: searxng
  labels:
    app: searxng
type: Opaque
stringData:
  settings.yml: |
    use_default_settings: true
    server:
      limiter: false
      image_proxy: false
      secret_key: "fb126e35af4997741f7e98a07ff03cec5bea340996a47790bd4d1d5b9902ec29"
    search:
      safe_search: 0
      autocomplete: ""
      default_lang: "en"
      formats:
        - html
        - json
